### PR TITLE
fix: strip response cache fields from incremental execution result

### LINKED ISSUE #2308: response-cache does not clear cache info from response for incremental delivery
### Issue workflow progress

When using the response cache plugin with incremental delivery (return stream from execute), the `__responseCacheId` and `__responseCacheTypeName` fields are not cleared from the parts.

image

### PR DESCRIPTION
**Pull request by n1ru4l**
closes https://github.com/n1ru4l/envelop/issues/2308

### CODE REVIEW

File: packages/plugins/response-cache/src/plugin.ts [hunk 1]
```diff
@@ -684,3 +690,26 @@ export const cacheControlDirective = /* GraphQL */ `
...
+  }
+  // clone the data to avoid mutation
+  data = { ...data };
+
+  if (data.__responseCacheTypeName) {
+    delete data.__responseCacheTypeName;
+  }
+  if (data.__responseCacheId) {
+    delete data.__responseCacheId;
+  }
```
Comment (EmrysMyrddin) [inline packages/plugins/response-cache/src/plugin.ts]: It is safe to delete things even if they don't exists
```suggestion
  delete data.__responseCacheTypeName;
  delete data.__responseCacheId;
```

**Review by EmrysMyrddin — APPROVED** [review]

**Review by dotansimha — APPROVED** [review]
