### PR TITLE
fix: handle introspection types per field

### LINKED ISSUE #892: operation-field-permissions: possibility to bypass the authorization
With the current implementation of skipping introspection queries, it is possible to bypass authorization by including `__schema` query in any other query

**To Reproduce**

add `__schema { __typename }` to any query to bypass authorization, like in the test:
```
query {
  __schema {
    __typename
  }
  greetings
}
```

### PR DESCRIPTION
**Pull request by dimatill**
## Description

Perform authorization for queries that contain `__schema` query.
Skip authorization for Introspection Types and nested fields.

Fixes #892 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/plugins/extended-validation/src/plugin.ts [hunk 1]
```diff
@@ -48,10 +48,6 @@ export const useExtendedValidation = (options: {
       const visitor = visitInParallel(rules.map(rule => rule(validationContext, args)));
       visit(args.document, visitWithTypeInfo(typeInfo, visitor));
 
-      for (const rule of rules) {
-        rule(validationContext, args);
-      }
```
Comment (dimatill) [inline packages/plugins/extended-validation/src/plugin.ts:53]: looks like it's not needed because of `rules.map(rule => rule(validationContext, args))` few lines above

But I'm not sure if this change should go with a separate PR. Please let me know if so

**Comment by dimatill** [comment]
looks like some checks are failed, I'll look into it later today

**Comment by dimatill** [comment]
> looks like some checks are failed, I'll look into it later today

rebased the branch and now all looks good :)

File: packages/plugins/operation-field-permissions/src/index.ts [hunk 2]
```diff
@@ -79,10 +76,23 @@ const OperationScopeRule =
...
+          const wrappedType = getWrappedType(type);
+
+          if (isIntrospectionType(wrappedType)) {
+            return false;
+          }
+        }
+
         const parentType = context.getParentType();
         if (parentType) {
           const wrappedType = getWrappedType(parentType);
```
Comment (dimatill) [inline packages/plugins/operation-field-permissions/src/index.ts]: as I can see it's not necessary to call `getWrappedType` here because `parentType` logically can't be a List nor NonNull type, and type definitions say that it is `GraphQLCompositeType`
```
export type GraphQLCompositeType =
  | GraphQLObjectType
  | GraphQLInterfaceType
  | GraphQLUnionType;
```

we can discuss it and if you agree then I can remove it in this PR or as a separate one

**Review by dotansimha — APPROVED** [review]
LGTM. 
Waiting for @n1ru4l 's review.

File: packages/plugins/extended-validation/src/plugin.ts (hunk 1 above)
Comment (n1ru4l) [reply packages/plugins/extended-validation/src/plugin.ts:53]: @dotansimha Ylu added this any comments? To me it also seems like we can drop this

File: packages/plugins/operation-field-permissions/src/index.ts (hunk 2 above)
Comment (n1ru4l) [reply packages/plugins/operation-field-permissions/src/index.ts]: We can remove it! Please do it 😇

**Review by n1ru4l — COMMENTED** [review]
Thank you for this! Please apply the other improvements and @dotansimha please check upon my comment, then we are free to merge 🎉

**Comment by dimatill** [comment]
> Thank you for this! Please apply the other improvements and @dotansimha please check upon my comment, then we are free to merge 🎉

Will do it!

File: packages/plugins/extended-validation/src/plugin.ts (hunk 1 above)
Comment (dotansimha) [reply packages/plugins/extended-validation/src/plugin.ts:53]: Oh, seems like a duplication? I guess it can be removed

File: packages/plugins/operation-field-permissions/src/index.ts (hunk 2 above)
Comment (dotansimha) [reply packages/plugins/operation-field-permissions/src/index.ts]: Agree!

**Comment by dimatill** [comment]
> > Thank you for this! Please apply the other improvements and @dotansimha please check upon my comment, then we are free to merge 🎉
> 
> Will do it!

Pushed it up

**Review by n1ru4l — APPROVED** [review]
